`timescale 1ns / 1ps

module uartRx (
    input  wire       clr,                          // global reset input
    input  wire       clk,                          // global clock input
    input  wire       ce16,                         // baud rate multiplied by 16 - generated by baud module
    input  wire       serIn,                        // serial data input
    output reg [7:0]   rxData,                       // data byte received
    output reg        newRxData                      // signs that a new byte was received
);

    wire        ce1;                                 // clock enable at bit rate
    wire       ce1Mid;                              // clock enable at the middle of each bit - used to sample data
    reg  [1:0] inSync;                              // input async input is sampled twice
    reg  [3:0] count16;                             // a counter to count 16 pulses of ce_16 to generate the ce_1 and ce_1_mid pulses
    reg        rxBusy;                              // receiving busy flag
    reg  [3:0] bitCount;                            // bit counter
    reg  [7:0] dataBuf;                             // data buffer shift register

    always @(posedge clk or posedge clr) begin
        if (clr) begin
            inSync <= 2'b11;
        end else begin
            inSync <= {inSync[0], serIn};
        end
    end

    always @(posedge clk or posedge clr) begin
        if (clr) begin
            count16 <= 4'b0;
        end else begin
            if (ce16) begin
                if (rxBusy || !inSync[1]) begin
                    count16 <= count16 + 1;
                end else begin
                    count16 <= 4'b0;
                end
            end
        end
    end

    always @(posedge clk or posedge clr) begin
        if (clr) begin
            rxBusy <= 1'b0;
        end else begin
            if (!rxBusy && ce1Mid) begin
                rxBusy <= 1'b1;
            end else if (rxBusy && (bitCount == 4'b1000) && ce1Mid) begin
                rxBusy <= 1'b0;
            end
        end
    end

    always @(posedge clk or posedge clr) begin
        if (clr) begin
            bitCount <= 4'b0;
        end else begin
            if (rxBusy && ce1Mid) begin
                bitCount <= bitCount + 1;
            end else if (!rxBusy) begin
                bitCount <= 4'b0;
            end
        end
    end

    always @(posedge clk or posedge clr) begin
        if (clr) begin
            dataBuf <= 8'b0;
        end else begin
            if (rxBusy && ce1Mid) begin
                dataBuf <= {inSync[1], dataBuf[7:1]};
            end
        end
    end

    always @(posedge clk or posedge clr) begin
        if (clr) begin
            rxData <= 8'b0;
            newRxData <= 1'b0;
        end else begin
            if (rxBusy && (bitCount == 4'b1000) && ce1) begin
                rxData <= dataBuf;
                newRxData <= 1'b1;
            end else begin
                newRxData <= 1'b0;
            end
        end
    end

    assign ce1 = (count16 == 4'b1111) && ce16;
    assign ce1Mid = (count16 == 4'b0111) && ce16;

endmodule