`timescale 1ns / 1ps

module uartTx (
    input  wire       clr,                          // global reset input
    input  wire       clk,                          // global clock input
    input  wire       ce16,                         // baud rate multiplied by 16 - generated by baud module
    input  [7:0]      txData,                      // data byte to transmit
    input  wire       newTxData,                    // asserted to indicate that there is a new data byte for transmission
    output reg        serOut,                       // serial data output
    output reg        txBusy                        // signs that transmitter is busy
);

    reg        [3:0]  count16;                      // counter to count 16 pulses of ce16 to generate ce1 pulse
    reg        [3:0]  bitCount;                     // output bit counter
    reg        [8:0]  dataBuf;                      // data shift register
    reg             ce1;                          // clock enable at bit rate
    reg               iTxBusy;                      // transmitter busy flag

    always @(posedge clk or posedge clr) begin
        if (clr) begin
            count16 <= 4'b0;
            //bitCount <= 4'b0;
            //dataBuf <= 9'b0;
            //ce1 <= 1'b0;
            //iTxBusy <= 1'b0;
           // serOut <= 1'b1;
        end else begin
            if (iTxBusy && ce16) begin
                count16 <= count16 + 1;
            end else if (!iTxBusy) begin
                count16 <= 4'b0;
            end
        end
    end

    always @(posedge clk ) begin
        if (clr) begin
            iTxBusy <= 1'b0;
        end else begin
            if (!iTxBusy && newTxData) begin
                iTxBusy <= 1'b1;
            end else if (iTxBusy && (bitCount == 4'b1001) && ce1) begin
                iTxBusy <= 1'b0;
            end
        end
    end

    always @(posedge clk ) begin
        if (clr) begin
            bitCount <= 4'b0;
        end else begin
            if (iTxBusy && ce1) begin
                bitCount <= bitCount + 1;
            end else if (!iTxBusy) begin
                bitCount <= 4'b0;
            end
        end
    end

    always @(posedge clk or posedge clr) begin
        if (clr) begin
            dataBuf <= 9'b0;
        end else begin
            if (!iTxBusy) begin
                dataBuf <= {txData, 1'b0};
            end else if (iTxBusy && ce1) begin
                dataBuf <= {1'b1, dataBuf[8:1]};
            end
        end
    end

    always @(posedge clk or posedge clr) begin
        if (clr) begin
            serOut <= 1'b1;
        end else begin
            if (iTxBusy) begin
                serOut <= dataBuf[0];
            end else begin
                serOut <= 1'b1;
            end
        end
    end


always@(*)
begin
if ((count16 == 4'b1111) && ce16)   
               ce1 = 1'b1;
else
    ce1 = 1'b0;
    txBusy = iTxBusy;
end
   
    

endmodule